puppetdb.conf, server_urls and storeconfigs = true
Without storeconfigs we get:

<pre>
 [puppetserver] Puppet You cannot collect exported resources without
storeconfigs being set; the collection will be ignored at
/etc/puppetlabs/code/environments/CCCP_1278/modules/haproxy/manifests/balancermember/collect_exported.pp:7:3
</pre>

Without server_urls and the puppetdb.conf we get

<pre>
Error: Could not retrieve catalog from remote server: Error 500 on
SERVER: Server Error: Failed to execute
'/pdb/cmd/v1?checksum=AAAAAAAA&version=5&certname=myhost1.example.org&command=replace_facts&producer-timestamp=1571642778'
on at least 1 of the following 'server_urls': https://puppetdb:8081
</pre>

The reports change is because
https://puppet.com/docs/puppetdb/5.2/connect_puppet_master.html said
that is a good idea.